spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jooq_db?allowMultiQueries=true
    username: jooq
    password: jooq

  jooq:
    sql-dialect: MySql
    render-name-case: AS_IS
    render-formatted: true

logging:
  level:
    org.jooq: DEBUG
    com.zaxxer: ERROR
    org.jooq.Constants: OFF
    org.jooq.tools.LoggerListener: OFF
    org.gh.CustomLoggerListener: DEBUG
  pattern:
    console: "%msg %n"